state-indexer/src/main.rs
The indexing speed of the `state-indexer` is way too slow. I suspect the logic around feeling up the table `account_access_keys`. I am disabling it to test the speed.
Once I am sure this causes the problem we will need to redesign the approach around this table completely.
=> refactor(state-indexer): Disable account_access_keys table

state-indexer/src/configs.rs, state-indexer/src/main.rs
This PR adds the `concurrency` parameter to the `state-indexer`.
It can be provided either via CLI arg:
```
state-indexer --concurrency 100 mainnet from-interruption
```
OR
via environmental variable:
```
env CONCURRENCY=100 state-indexer mainnet from-interruption
```
=> feat(state-indexer): Add concurrency config parameter

Cargo.lock, state-indexer/src/configs.rs, state-indexer/src/main.rs, state-indexer/src/metrics.rs, tx-indexer/Cargo.toml, tx-indexer/src/config.rs, tx-indexer/src/main.rs, tx-indexer/src/metrics.rs
Sometimes it’s necessary to have a quick look to get the blocks per second speed of the indexer.
This pr implements calculator the BPS(blocks per second) and report it in the log message once in 10 second.
=> DPLT-968: Indexer BPS log

Cargo.lock, tx-indexer/Cargo.toml, tx-indexer/src/collector.rs, tx-indexer/src/config.rs, tx-indexer/src/main.rs, tx-indexer/src/storage.rs
This PR introduces the `tracing-instrumentation` feature to the `tx-indexer` crate, following the same approach as PR #58.
I have tested the changes locally, and there don't seem to be any major issues. Most of the tasks have been properly parallelized, with the exception of `update_meta`, which doesn't add significant overhead.
=> refactor(tx-indexer): Add tracing-instrumentation feature to the tx-indexer

state-indexer/src/configs.rs
This PR fixes the paths to `HashMap` hidden under the feature.
=> fix(state-indexer): Fix path to HashMap under tracing-instrumentation feature

tx-indexer/src/config.rs
I've noticed an error appearing from time to time:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TransportError(SendError(PayloadSendError(reqwest::Error { kin
d: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rpc.mainnet.near.org")), port: None, path: "/", query:
None, fragment: None }, source: hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) })))', tx-indexer/src/config.rs:133:51
tx-indexer_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And then I found the `.unwrap` where it didn't belong to.
=> fix(tx-indexer): Drop redundant unwrap in `final_block_height` function leding to errors

database/src/lib.rs, rpc-server/src/config.rs, rpc-server/src/main.rs, state-indexer/src/configs.rs, state-indexer/src/main.rs, tx-indexer/src/config.rs, tx-indexer/src/main.rs
This pr implement  a retry logic for the cases when we get an error from ScyllaDB and we cannot miss the data.
For indexers works in so-called “strict” mode when we retry infinitely though throwing a warning about it. In addition, we have a “non-strict” mode that limits the number of retries to N (5 by default).
For rpc-server works “non-strict” mode with limits the number of retries to 2.
=> DPLT-1018: Introduce retries to the indexers writes to ScyllaDB

state-indexer/README.md, state-indexer/src/configs.rs, tx-indexer/README.md, tx-indexer/src/config.rs
This PR introduces an optional fallback start from the block value to the `from-interruption` start mode.
One can run the following command:
```
$ env INDEXER_ID="state-indexer-1" state-indexer mainnet from-interruption 90000000
```
The value `90000000` will be used if the database has no record for the `last_processed_block_height` value stored for the indexer with ID `state-indexer-1`.
The fallback value is optional. If not provided in case of error the indexer will fall back to the `from-latest` value.
=> feat(indexers): Add optional fallback value to the `from-interruption` start mode

rpc-server/Cargo.toml, rpc-server/Dockerfile, rpc-server/README.md, rpc-server/src/modules/transactions/methods.rs
We are preparing for the test lunch of the project. We're not going to make it public yet, but instead, we're going to mirror the traffic to the read-rpc-server to catch bugs and inconsistencies.
We want to disable methods that send transactions to the real NEAR RPC to avoid potential problems for the users.
This PR introduces a default feature flag `send_tx_methods` that enables methods:
- `broadcast_tx_commit`
- `broadcast_tx_async`
Once the feature is disabled those methods are still available in the API but respond with errors instead.
Also in this PR, I did the following:
- Added section "Feature flags" to the `rpc-server`'s README
- Updated the `rpc-server`'s `Dockerfile` for our deployment to disable the default feature I've added
=> refactor(rpc-server): Hide send transaction methods under the feature `send_tx_methods` (default)

Cargo.lock, README.md, docker-compose.yml, tx-indexer/Cargo.toml, tx-indexer/Dockerfile, tx-indexer/src/config.rs
This is an initial version of the `docker-compose.yml` for running the project locally.
I've left a "TODO" section about the Docker compose in the README with the things I want us to improve in the future:
- Setup all the services to use volumes for the codebase and use `cargo watch` to recompile the code on the fly
- Come up with a way of changing the configuration for the indexers in a convenient way
- Robust documentation for the docker-compose setup
=> feat: Docker-compose file to run the project locally

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/utils.rs
Essentially, this PR does what the title says.
The goal was to refactor the `shadow_compare_results` function from the feature `shadow_data_consistency`. We wanted to change the way the function can be used as a result of this refactor.
Initially, the function `shadow_compare_results` were emitting log-messages. However, we find it inconvenient and wanted to be able to use this function a little bit differently.
That's why this PR introduces an error structure `ShadowDataConsistencyError` (hidden behind the same feature-flag)
```
/// Represents the error that can occur during the shadow data consistency check.
#[cfg(feature = "shadow_data_consistency")]
#[derive(thiserror::Error, Debug)]
pub enum ShadowDataConsistencyError {
#[error("Failed to parse ReadRPC response: {0}")] …
```
=> refactor(rpc-server): Refactor shadow_compare_results function to return ShadowDataConsistencyError

rpc-server/src/modules/queries/methods.rs
While the refactoring of other methods is not finished yet, we're trying to improve the logging around the `query` method. #77 PR has improved it a bit, but we find it still hard to read the errors from `shadow_data_consistency` since it's hard to identify what the call was. 
This small PR aims to address it.
=> refactor(rpc-server): Improve logging in shadow_data_consistency around query method

rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/utils.rs
For now, we want to ensure Read RPC error is expected by doing a shadow call to the real RPC
This pr include refactoring next methods:
`block `
`chunks`
`EXPERIMENTAL_changes`
`EXPERIMENTAL_changes_in_block`
=> DPLT-1033: refactoring(rpc_server) `block` and `chunk` methods

rpc-server/src/modules/queries/methods.rs
This PR resolves the second batch of identified bugs/errors from Traffic mirroring phase 1 (#82):
- Change the error returned by `query.view_code` when there is no account (`NO_CONTRACT_CODE` -> `UNKNOWN_ACCOUNT`) as NEAR JSON RPC does
- Remove redundant warning log from the helper functions of the `query` method.
=> fix(rpc-server): Fix Traffic mirroring bugs/errors phase 1, batch 2

readnode-primitives/src/lib.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/transactions/methods.rs
We had to filter out local receipts (ref: https://stackoverflow.com/questions/67678135/what-is-local-receipt-in-near-protocol) from the Read RPC responses. There are a couple of reasons for that:
1. `nearcore` doesn't store local receipts in the first place. Thus, NEAR JSON RPC doesn't include them in the responses. You won't get it even asking for them directly via the `EXPERIMENTAL_receipt` method. *RR does, however*.
2. NEAR Indexer Framework, on the other hand, exposes such receipts, which are stored in Lake S3. Since we're using S3 as a data source, Read RPC includes those receipts in the response, but we have to be consistent with the original NEAR JSON RPC.
Having the above statements, I've asked @kobayurii to filter out the local receipts from the responses. However, I misled him …
=> refactor: Improve local receipt exclusion for tx-related methods. Revert the logic for chunks.

readnode-primitives/src/lib.rs, rpc-server/src/modules/blocks/utils.rs
In my previous PR #88, I missed the crucial indicator of the local receipts (the sender is 
the receiver, to be precise). This PR fixes my mistake.
=> fix: Local receipt handling (missed important indicator of the local receipt)

rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs
There is an assumption that optimistic queries we don’t support in the Read RPC (yet) cause most errors. 
This PR remove optimistic requests from the error counters.
Added SYNC_CHECKPOINT_REQUESTS_TOTAL counter.
=> DPLT-1045: Remove optimistic queries from error counters

rpc-server/src/config.rs, rpc-server/src/modules/blocks/utils.rs
In this pr we added retrying to fetch object from s3. We add new function fetch_object_from_s3_with_retry in which we try to get object from s3 three times if we have some problem with network, otherwise we return an error.
=> Improvement(rpc-server): Add retrying to fetch object from s3

rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
https://github.com/near/read-rpc/issues/92
In this pr we improve shadow_data_consistency logs. 
Data may mismatch in 4 cases:
1. Both services(read_rpc and near_rpc) have a successful response 
if data mismatch we are logging into `shadow_data_consistency_successful_responses`both response objects for future investigation.
2. read_rpc - failure, near_rpc - successful
we are logging into `shadow_data_consistency_read_rpc_failure_response` just message about mismatch data without objects. In the future we should be investigate why we got error in the read_rpc.
3. read_rpc - successful , near_rpc - failure
we are logging into `shadow_data_consistency_near_failure_response` just message about mismatch data without objects. Expected that all error will be related with network issues.
4. Both …
=> Improvement(rpc-server): Add additional logs for `shadow_data_consistency`

Cargo.lock, docker-compose.yml, rpc-server/Cargo.toml, rpc-server/README.md, rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
Resolves #97 
In this PR my goal was to disambiguate the error counters to reflect different (known) reasons for the errors. I achieve this by renaming the existing metrics and adding the code as a suffix. 
Yeah, I am aware of the antipattern of "magic numbers", but I want to keep the metric names shorter. Here's the list of the available codes (also, I've added this info to the `rpc-server` README).
> - **0** - ReadRPC returns a Success result, and NEAR RPC returns a Success result, but the results don't match
> - **1** - ReadRPC returns Success result, and NEAR RPC returns an Error result
> - **2** - ReadRPC returns an Error result, and NEAR RPC returns Success result
> - **3** - ReadRPC returns an Error result, and NEAR RPC returns an Error result, but the results don't match
> - **4** …
=> refactor(rpc-server): Split error metrics to disambiguate the error reasons

rpc-server/src/main.rs
Currently, we run only one instance of the ReadRPC-server for traffic mirroring (with the`shadow_data_consistency` feature enabled). This instance receives a copy of the traffic from the Archival RPC nodes (some or all of the traffic doesn’t matter).
However, for the shadow calls, ReadRPC does the call to an Archival RPC. Recently internal and public archival RPC nodes were merged together, and the SRE team set up a feature that the request with the header `Referer: read-rpc` won’t be mirrored back to the ReadRPC.
We need to ensure ReadRPC includes this header in shadow calls.
I've added a `TODO` there to make it configurable in the future but hardcoded to handle the circulating requests issue for now.
=> refactor(read-rpc): Add header referer: read-rpc to near-jsonrpc-client

rpc-server/src/utils.rs
This PR naively removes the `metadata` field from the JSON responses being compared during the `shadow_data_consistency` check. 
This field is not backward compatible on the `nearcore` side, it is used mainly for debugging, and different `nearcore` nodes can respond with different data in that field. But it harms our shadow data checks, so we want to ignore this field completely.
=> refactor(rpc-server): Shadow data consistency call to ignore `receipts_outcome.outcome.metadata`

rpc-server/src/utils.rs
The majority of mismatch errors for the `EXPERIMENTAL_tx_status` call contain the error from Archival RPC `TIMEOUT_ERROR`, which is handled as a `MismatchError` while it should be as `NearRpcCallError`.
I've made it in a hacky way. However, **I wasn't able to properly check it locally** since I've failed to reproduce the `TIMEOUT_ERROR`. This should work, but I must check it on the server after merging and fix/adjust it if necessary.
=> refactor(rpc-server): Make shadow_data_consistency check handle `TIMEOUT_ERROR` as `NearRpcCallError`

rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/storage.rs, state-indexer/src/configs.rs
I initially intended to fix the `query` method to return an honest block reference in the response.
All the responses of the `query` method with all its `request_type` contain `block_height` and `block_hash`. On the NEAR RPC side, those fields highlight the "time" the data is up-to-date. 
On the ReadRPC side, however, we put the block reference of the requested block there.
What does it mean? If you request the data for block 100 but indexers haven't collected the data for block 100, the ReadRPC will return the latest available data for block 99, for example. But in the response, block 100 will be included in those `block_height` and `block_hash` fields.
This unfair behavior can be misleading, making debugging a bit more complex.
So I would ensure we include the `block_height` from the …
=> refactor(rpc-server): storage refactoring

rpc-server/src/modules/queries/methods.rs
This is a follow-up for the #105 PR.
Shadow data consistency check for the methods accepting `block_reference` is being done for the specific block even if the original request was at `finality: final`. This is done because we want to compare the data at a given time (and compare block N with the real final block, where N is different from the final block height, which would lead to a mismatch guaranteed is not what we want). 
In this PR I adjust the block height propagating for the shadow call by taking the block height from the query-method response instead of a final block height from the cache. I left comments around it for future us.
=> refactor(rpc-server): Adjust shadow-data-consistency check for QUERY method

rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
In this PR we added `reason.code()` in to `shadow_consistency_error` logs. This will add the ability to filter logs entries by a specific `code`.
=> Add reason code into the shadow consistency error log

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/errors.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/utils.rs
This PR includes improvement for `query:function_call`
1. Added `random_seed` for function_call
2. Moved `max_gas_burnt` into the configuration options
3. Added an error handler to function_call the same as in NEAR RPC so that the error responses coincide.
=> ND-604: query.function_call different results

rpc-server/src/modules/queries/methods.rs, rpc-server/src/storage.rs
In this PR fixed `query.view_access_key` error response mismatch
=> ND-608: query.view_access_key error response mismatch

rpc-server/src/modules/queries/methods.rs, rpc-server/src/storage.rs
In this PR we solve problems with a lot of errors with view_access_key when Read RPC error, but NEAR RPC success.
=> ND-609: query.view_access_key response mismatch

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/cache.rs, rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/utils.rs
We have a problem that the service crashes from time to time with an OOM error. This is most likely related to caching. I added a memory wrapper around the LRU сaсhe to avoid such situations. I also added the ability to set cache parameters via configuration. To make sense of the situation, I added information to the status method which returns the memory’s information on the server and how much memory cache takes up.
=> ND-541: Read RPC server dies with OOM from time to time

rpc-server/src/modules/queries/utils.rs
since near_vm_runner = 0.16.1, we no longer need to manually call  `precompile_contract`. It is done inside the near_vm_runner. And for VM Configs we got new options `free`
=> function_call improvement

database/src/lib.rs
In this PR we change consistency to LOCAL_ONE for read queries and to LOCAL_QUORUM for writes.
- LOCAL_ONE (especially for reads) if you don't care about the consistency of your reads, as in possibly reading old/stale data.
- LOCAL_QUORUM (always for writes) to ensure you have at least QUORUM writes on the LOCAL datacenter before the app is satisfied. This will grant you at least 66% sure that the LOCAL_ONE query will reads the most up-to-date data all the time.
=> change consystensy level for scylla db

tx-indexer/src/config.rs, tx-indexer/src/main.rs, tx-indexer/src/storage/database.rs
In this PR we added a paginator in to query to read all transactions in the process. We did it because Scylla db failed when we tried to scan all rows in the table on start.
=> add paginator into cache storage

database/src/lib.rs
After repairing Scylla DC if we want to 100% guarantee data correctness and data consistency, Scylla Team recommended set to read + write with CL=LOCAL_QUORUM to accomplish CL=W + CL=R > RF --> 2/3 + 2/3 > RF=3 --> 4 > 3
=> change consistency level for read queries on LocalQuorum

rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/clients/methods.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
This pull request is a comprehensive enhancement that resolves the existing issue pertaining to NEAR_RPC_URL configuration and optimizes Remote Procedure Call (RPC) handling within the project.
1. Added NEAR_RPC_URL as the Regular RPC endpoint.
2. Added ARCHIVAL_NEAR_RPC_URL as an optional setting for Archival RPC endpoints.
3. Added logic to utilize Archival RPC selectively for specific use cases, like shadow_data_consistency.
This pull request aims to improve RPC configurations and usage, enhancing the project's efficiency and performance while providing more granular control over RPC endpoints for different functionalities.
=> feat: Require NEAR regular RPC URL additionally in configs

rpc-server/Cargo.toml, rpc-server/Dockerfile, state-indexer/Dockerfile, tx-indexer/Dockerfile
Previously, I have messed up the feature of enabling/disabling proxying write methods (send-tx ones).
The feature name declared in the `Cargo.toml` of the project was not the same as in the code 😅.
This PR fixes it, and I confirm that sending transactions through ReadRPC via `near-cli-rs` works like a charm.
Also, `Dockerfile`s we have with the `ARGS feature="` declines the default feature on the build, so I had to add a `default` value there.
For future reference, if you want to build a project with default features and some additional one(s), you need to pass `--build-arg="features=default, another_feature"` (include the **default** word) in the `docker build` command.
=> fix(rpc-server): Fix the name of the feature in the `Cargo.toml` that enables write-methods proxy

rpc-server/Dockerfile, state-indexer/Dockerfile, tx-indexer/Dockerfile
In the https://github.com/near/read-rpc/pull/139 we used `[patch.crates-io]` which should be grown at the top level.
During the build, we ignored this patch and therefore received a message about unavailable dependencies. 
Now we leave the Cargo.toml and remove the unnecessary modules when building.
=> fix docker build

rpc-server/Dockerfile, state-indexer/Dockerfile, tx-indexer/Dockerfile
fix error:
```./read-rpc-server: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory```
=> update ubuntu version for docker

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/main.rs
This PR adds a setup for CORS to allow any origin to enable querying the server from the browser (required for NEAR BOS-component integrations)
=> refactor(rpc-server): Add CORS to allow any origin

database/src/base/rpc_server.rs, database/src/postgres/rpc_server.rs, database/src/scylladb/rpc_server.rs, rpc-server/src/modules/queries/mod.rs, rpc-server/src/modules/queries/utils.rs
**Changes Implemented**
**1. Removed Key Limit:** The previously imposed limitation on the number of keys in a state has been eliminated. This means our system can now handle a larger volume of keys without restrictions.
**2. Optimization of Queries:** We've implemented optimizations for both key and value queries. This enhancement ensures improved efficiency and performance when retrieving information related to keys and their corresponding values.
**Temporary Solution**
It's important to note that while these changes represent a substantial improvement, this solution is temporary. Although the system now allows for handling a greater number of keys, there's no absolute guarantee for handling exceptionally large datasets, such as those in the gigabyte range.
**Future Steps**
**1. …
=> remove `view_state` limit

rpc-server/src/main.rs
Previous PR #143 used to work during the local check but suddenly stopped. This one makes sure it's working.
=> fix(rpc-server): Set permissive CORS

rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params"},"id":"dontcare"}
=> fix validator parse error 

Cargo.lock, database/Cargo.toml, database/src/base/mod.rs, database/src/base/rpc_server.rs, database/src/lib.rs, database/src/postgres/models.rs, database/src/postgres/rpc_server.rs, database/src/scylladb/rpc_server.rs, rpc-server/src/main.rs, rpc-server/src/modules/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/modules/state/methods.rs, rpc-server/src/modules/state/mod.rs, rpc-server/src/modules/state/utils.rs
This pull request introduces a new API endpoint named `view_state_paginated` designed to facilitate paginated viewing of contract states.
New Endpoint: `view_state_paginated`
1. This endpoint is specifically crafted to facilitate paginated requests for retrieving contract states.
2. Implements the necessary logic to fetch contract states in paginated form based on specified parameters.
The primary objective of this addition is to enhance the contract management functionality by providing a more efficient and organized method to access contract states. The paginated view enables users to retrieve contract states in smaller, manageable segments, thereby improving system performance and simplifying navigation, especially when dealing with extensive contract data.
=> (rpc-server): add new endpoint view_state_paginated

Cargo.lock, database/src/base/rpc_server.rs, database/src/base/state_indexer.rs, database/src/postgres/migrations/2023-12-07-144820_epochs/up.sql, database/src/postgres/models.rs, database/src/postgres/rpc_server.rs, database/src/postgres/schema.rs, database/src/postgres/state_indexer.rs, database/src/scylladb/rpc_server.rs, database/src/scylladb/state_indexer.rs, epoch-indexer/src/config.rs, epoch-indexer/src/lib.rs, epoch-indexer/src/main.rs, perf-testing/src/chunks.rs, readnode-primitives/src/lib.rs, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/errors.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs, rpc-server/src/modules/queries/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/modules/state/utils.rs, rpc-server/src/utils.rs, state-indexer/src/main.rs
The current implementation faces a challenge where information about validators during an epoch in Near operations may undergo changes. The StakeAction, acting as a trigger for these changes, is not properly considered by the indexer. As a result, the indexer neglects to update validator information when StakeAction occurs, leading to incomplete and inaccurate data about validators for that epoch.
In this PR:
1. Configured the system to save comprehensive information about validators at the conclusion of each epoch. This ensures that the indexer captures and indexes the most up-to-date data about validators, eliminating the issue of incomplete information.
2. Added functionality to include information about the last block of the epoch in the indexing process. This addition ensures that …
=> (state-indexer): Bug with indexing epoch validators info

rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs
If a chunk does not exist - we get an error on the read RPC server from the database about the absence of a chunk in the form:
{"info":  { "error_message": "Expected a single row, found 0 rows"}, "name": "INTERNAL_ERROR"}
In this PR we improve the handling of errors and make the errors look like:
{"info": { "chunk_hash": {chunk_hash}}, "name": "UNKNOWN_CHUNK"}}
=> (rpc-server): chunks - Mismatch error message

config.toml, configuration/example.config.toml, configuration/src/configs/general.rs, rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
This pull request introduces a new parameter, shadow_data_consistency_rate, which offers the opportunity to compare a subset of results rather than the entirety of data. With this enhancement, users can specify a percentage of data to be compared for each request method, optimizing resource utilization and providing flexibility in data validation processes.
New Parameter: `shadow_data_consistency_rate`
1. This parameter allows users to define the percentage of data to be compared for each request method.
2. Default value: 100% (all data compared).
3. Range: 0% to 100%
4. Use-case: Users can set a lower percentage to perform partial data validation, reducing computational overhead.
Benefits:
1. Resource Optimization: Users can conserve resources by selectively validating a portion of data, …
=> add shadow data consistency rate

CHANGELOG.md, rpc-server/src/config.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/queries/methods.rs
1. Rewrite the method to get genesis_block from `lake_framework` to avoid the call to archive nodes.
2. Added `archive_proxy_query_view_state_with_include_proofs` metric to calculate count of requests to the archive nodes
3. Added separation of calls in the `QUERY.VIEW_STATE` method with the `include_proof` flag into regular and archive nodes
=> Additional metrics to measure proxy calls (archival)

CHANGELOG.md, readnode-primitives/src/lib.rs, rpc-server/src/modules/queries/methods.rs
Some time ago, while we were actively developing and debugging the storage of the ReadRPC, we introduced a change in the logic different from the `nearcore` JSON-RPC API. Thus, we started to respond with the `block_height` and `block_hash` in the `query` method responses with the block data around the block **we observed the last change to the data** instead of the block we observed the data at. 
*Please feel free to ask in the comments if my explanation is confusing**
This PR reverts that logic to follow the `nearcore` one. Now, we will respond with the final block from the ReadRPC point of view when we ask. 
@kobayurii, we could have adjusted the `shadow_data_consistency` logic for this check. We don't need to match the blocks since it won't match anyway, but perhaps some additional …
=> refactor: Revert the logic behind the responding block_height and block_hash in query method

CHANGELOG.md, docs/RPC_METHODS.md, rpc-server/src/config.rs, rpc-server/src/health.rs, rpc-server/src/main.rs, rpc-server/src/modules/network/methods.rs
This pull request addresses the issue #181 of implementing the status method, enhancing its functionality to enable the return of `near_primitives::views::StatusResponse`.
* Implemented the `status` method to accommodate `near_primitives::views::StatusResponse`.
* Implemented the `health` method. Health includes the info about the syncing state of the node of `rpc-server`.
=> [status] Implement `status` method that is able to return `near_primitives::views::StatusResponse`

rpc-server/src/metrics.rs, rpc-server/src/utils.rs
In this pull request, we add two additional metrics:
1. proxy_request_to_regular_nodes_counter
2. proxy_request_to_archival_nodes_counter
This should help to investigate how many requests we proxies to near nodes
=> add metrics to count proxies requests

rpc-server/src/metrics.rs, rpc-server/src/modules/clients/methods.rs
This pr includes two changes:
1. Added  archival proxies for methods `light_client_proof` and `next_light_client_block`
2. Added metrics to count archival proxies: `archive_proxy_light_client_proof` and `archive_proxy_next_light_client_block`
=> add archival proxy `light_client_proof` and `next_light_client_block`

Cargo.lock, Cargo.toml, config.toml, configuration/example.config.toml, configuration/src/configs/general.rs, database/src/base/state_indexer.rs, near-state-indexer/Cargo.toml, near-state-indexer/src/main.rs, near-state-indexer/src/utils.rs, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/health.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/utils.rs, state-indexer/src/main.rs
In this pull request, we introduce support optimistic blocks. 
Recently we've added additional metrics to measure the number of proxy requests from the ReadRPC to the native one. Additionally, we have a metric that counts how many of the requests are for the blocks with optimistic finality. This finality is not yet supported in the ReadRPC. The metrics revealed that a significant portion of the requests are for the optimistic blocks - 85% of all requests.
Implementation of `optimistic_blocks` support will help to reduce the number of proxied requests and help to optimize and speed up the service.
=> Implement support for optimistic block finality

.github/workflows/release.yml
This PR introduces a GitHub Action to automate building the `near-state-indexer` binary. 
It streamlines the compilation process and enhances project workflow efficiency.
=> Create GitHub Action to build a binary for `near-state-indexer`

Cargo.lock, Cargo.toml
This PR update new nearcore dependencies which include necessary fixes for near-indexer.
More details read in this PR: https://github.com/near/nearcore/pull/10798
=> chore: release 0.2.2

rpc-server/src/modules/transactions/methods.rs, rpc-server/src/modules/transactions/mod.rs
In this PR  we added support new and old request style for transactions:
**old:** 
```{
"jsonrpc": "2.0",
"id": "dontcare",
"method": "tx",
"params": ["67JtSzundU2tt2wEoJYhf527QBRHSxC5FW8KDBWGbA6H", "hotwallet.kaiching"]
}
```
**new:**
```{
"jsonrpc": "2.0",
"id": "dontcare",
"method": "tx",
"params": {
"tx_hash": "67JtSzundU2tt2wEoJYhf527QBRHSxC5FW8KDBWGbA6H",
"sender_account_id": "hotwallet.kaiching"
}
}
```
=> tx request returns "Invalid params" to a totally valid request

Cargo.lock, database/src/base/tx_indexer.rs, database/src/postgres/tx_indexer.rs, database/src/scylladb/rpc_server.rs, database/src/scylladb/tx_indexer.rs, tx-indexer/Cargo.toml, tx-indexer/src/collector.rs
For some unknown reason, tx-indexer saves invalid data for transactions. We want to avoid these problems and get more information. That's why we added a mechanism to check and resave transactions. We have also expanded logging so that we can determine the causes in more detail.
=> add warning when we could't borsh dezerialize tx deteils

CHANGELOG.md, Cargo.lock, Cargo.toml, database/src/scylladb/tx_indexer.rs, near-state-indexer/src/main.rs, near-state-indexer/src/utils.rs, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/utils.rs
This PR includes changes:
1. Update nearcore dependencies to 1.39.0 
2. Improvement logic to set and get finalities blocks from Redis
=> Update nearcore to 1.39.0

rpc-server/src/modules/blocks/methods.rs
This PR includes improvements to the error text when receiving a block. 
This is to maintain full compatibility with the native NEAR RPC.
issue: https://github.com/near/read-rpc/issues/228
=> (rpc-server): UNKNOWN_BLOCK error response mismatch

rpc-server/src/main.rs, rpc-server/src/utils.rs
We need to update final block from Redis and Lake because we can't be sure that Redis has the latest block.
Lake can be used as a backup source
=> final block handler improvement

rpc-server/src/modules/network/methods.rs
Temporary fix. For the future, it should handle epoch config. 
https://github.com/near/read-rpc/issues/239
=> fix protocol_version for protocol config

rpc-server/src/metrics.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/utils.rs
When we call `near_vm_runner::run` method accepts the code: Option<&ContractCode>
ref: https://github.com/near/nearcore/blob/14334b9e4e2bff198537130324f2bb9702f54d6d/runtime/near-vm-runner/src/runner.rs#L46
And following down the road, it appears that if this value is None, it is a signal for the near-vm-runner to compile the contract even if we have it in the cache, and it hasn't changed ever since.
After updating nearcore to 1.39.x we use the near-vm-runner crate incorrectly 🤦‍♂️ We naively pass the code every time, hoping near-vm-runner handles it automatically, but it appears it does not.
=> (rpc_server): Performance problem ft. near-vm

.github/workflows/checks.yml
We recently introduced a `develop` branch to separate the production-ready code from the one being developed.
This small PR enables the GH Actions checks for the new branch
=> chore: Enable GitHub action checks workflow for develop branch

near-state-indexer/src/utils.rs
In this pr, we improve the process to update finalities blocks. 
When running multiple indexers, we should avoid competitiveness in updating the finalities blocks streamer message in the redis.
=> improvement to save finalities blocks streamer_message

near-state-indexer/src/utils.rs
The issue is relatively small and the only outcome of it was a bunch of warning, the logic was intact.
=> fix(near-state-indexer): Fix the TypeError in communication with Redis leading to spam of warnings

database/src/scylladb/rpc_server.rs
We have identified an issue with transaction hash collisions in the NEAR protocol, as detailed in [issue #84](https://github.com/near/near-indexer-for-explorer/issues/84). Specifically, there is an inconsistency in how transactions with the same hash are handled by different RPC endpoints.
**Issue**
- _RPC Near Protocol:_ Returns the first transaction for a given hash.
- _Read-RPC Server:_ Returns the last transaction for a given hash.
This discrepancy can lead to confusion and potential errors in transaction processing and data retrieval.
**Solution**
This pull request aims to standardize the behavior across both RPC endpoints to ensure consistent and predictable results when querying transactions by hash.
**Changes**
- Modify the query in the Read-RPC server to the ScyllaDB to align …
=> fix(rpc-server): Fix of the returned transaction results associated with the transaction hash collisions.

rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs
This pull request introduces new metrics for categorizing blocks based on their age and relevance. 
The categories added are:
- optimistic
- final
- regular (5 epochs)
- historical (more than 5 epochs)
These new metrics will enable us to track and analyze the frequency and distribution of different block queries. Understanding the usage patterns will help us to optimize our caching strategy, improving performance and efficiency.
=> Metrics(rpc-server): Extend metrics

docs/CUSTOM_RPC_METHODS.md, readnode-primitives/src/lib.rs, rpc-server/src/main.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/receipts/mod.rs
Here's an example of calling `view_receipt_record`:
closes #264
=> feat: added `view_receipt_record` rpc endpoint

rpc-server/src/modules/queries/methods.rs
The temporary solution is to avoid a lot of read queries to the database.
During contract execution, we provide the host function to the contract runner, which fetches the key directly from ScyllaDB. This works great for most contracts that require a few keys during execution.
The problem with this approach shows itself during the Staking Pool contract call of the method get_accounts
```
pub fn get_accounts(&self, from_index: u64, limit: u64) -> Vec<HumanReadableAccount> {
let keys = self.accounts.keys_as_vector();
(from_index..std::cmp::min(from_index + limit, keys.len()))
.map(|index| self.get_account(keys.get(index).unwrap()))
.collect()
}
```
=> hook(rpc-server): Proxy *poolv1.near contracts on function_call

database/src/base/rpc_server.rs, database/src/postgres/models.rs, database/src/postgres/rpc_server.rs, database/src/scylladb/rpc_server.rs, rpc-server/src/config.rs, rpc-server/src/metrics.rs, rpc-server/src/middlewares.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/clients/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
In this PR Historical/regular counter is extended and broken down by method.
This metric should to help to analyze the block_references for methods 
to see the most common pattern is it specific block or final/optimistic.
- final
- optimistic
- block_id:
- regular - includes 5 last epochs
- historical - later than 5 epochs ago
=> (rpc_server): Extend metrics

examples/postgres-compose.yml, examples/rightsizing-compose.yml, rpc-server/README.md, rpc-server/src/main.rs, rpc-server/src/utils.rs
Before: 
After:
To complete this, I've added redis dependency to postgres and rightsizing docker-compose files
In any case we can merge these minor fixes now and later (@kobayurii @khorolets) will decide wether Redis is required or not
closes #274 
closes #279
=> fix: clarified Redis connection errors and added Redis dependency to docker-compose files

CHANGELOG.md, Cargo.lock, Cargo.toml, rpc-server/Cargo.toml, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs, rpc-server/src/modules/queries/contract_runner/code_storage.rs
WIP: there are some breaking changes around `near-vm-runner` we need to adapt
* Upgrade dependencies for supporting `nearcore-1.40.0`
=> chore: Upgrade to nearcore 1.40.0

CHANGELOG.md, Cargo.lock, Cargo.toml, config.toml, configuration/example.config.toml, configuration/src/configs/mod.rs, configuration/src/configs/tx_details_storage.rs, database/src/scylladb/tx_indexer.rs, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/modules/transactions/mod.rs, tx-details-storage/Cargo.toml, tx-details-storage/README.md, tx-details-storage/src/lib.rs, tx-indexer/Cargo.toml, tx-indexer/src/collector.rs, tx-indexer/src/main.rs, tx-indexer/src/metrics.rs, tx-indexer/src/storage.rs
We noticed that the `transaction_details` table in ScyllaDB takes ~2 TB of data, directly affecting the infra cost. We want to reduce the cost even more. Building on our successful experience of serving some data directly from the NEAR Lake AWS S3 storage, we propose to move the `TransactionDetails` data to object storage (GSC) to further offload ScyllaDB.
Since this structure is stored in bytes (borsh-serialized), it doesn't make any big difference to the performance (though some increase in latency, anyway, is expected, not that significant to overpay).
1. I've introduced a small crate (lib) `tx-details-storage` that interacts with the provided S3-compatible object storage to store and retrieve raw bytes
2. Extended the `configuration` crate with the dedicated config section for …
=> feat: Store `TransactionDetails` in object storage (GCS) 

rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/mod.rs, tx-indexer/src/collector.rs
* (read-rpc) Fall back to legacy database if tx failed to read from bucket (deserialization error, or not found)
* (read-rpc) Change the method of getting the tx for `EXPERIMENTAL_receipt`
* (tx-indexer) Adjust timeouts for saving and validating the tx_details, adjust log levels
=> fix: rpc-server tx fallback to legacy improve, tx-indexer adjust timeouts and log levels

Cargo.lock, configuration/src/configs/lake.rs, configuration/src/configs/tx_details_storage.rs
In my investigations about the abnormal amount of the error messages from AWS client I've encountered this issue.
Following the advice to disable the newly introduced `StalledStreamProtection` which seemed to be the root cause led me to the results I was aiming for.
This fix should resolve the problem of storing `tx_details` to GCS. I tested it locally to prove it helps.
=> fix(configuration): AWS ThroughPutBelowMinimum errors and timeouts

configuration/example.config.toml, configuration/src/configs/general.rs, rpc-server/src/config.rs, rpc-server/src/modules/queries/contract_runner/code_storage.rs, rpc-server/src/modules/queries/contract_runner/mod.rs, rpc-server/src/modules/queries/methods.rs
This PR introduces a configuration option to control the maximum size of storage used for state prefetching during a `view_call`. Prefetching helps to speed up the `view_call` by loading data in advance, but it can consume more time if state size is too big. To prevent excessive time usage during a `view_call`, we set a default limit of 1MB (1_000_000 bytes) for the prefetch storage. Prefetching will only be an option if the state storage usage is below this given threshold
=> feat: prefetch optimization

logic-state-indexer/src/configs.rs, near-state-indexer/src/configs.rs, near-state-indexer/src/main.rs, perf-testing/src/config.rs, rpc-server/src/main.rs, state-indexer/src/main.rs, tx-indexer/src/config.rs, tx-indexer/src/main.rs
I've added the version flag for all indexers. However, I didn't complete the part with a supported nearcore version. In order to print an information about nearcore version along with the indexer version, we need to store nearcore version in some env variable (or in .toml file). I'm not sure that this overhead is needed, but I'm more than happy to implement it, so please say if this small overhead worth it or not
closes #287
=> feat: added support for a `version` flag

rpc-server/src/modules/queries/methods.rs
This PR closes #302. Basically current fix is very straightforward, therefore it might not be very optimal. We simply check whether an account exists in our DB and handle "Unknown account" error before fetching the state. If we didn't exit function during the check, then we print the state no matter of its value (even if the state is empty). I also thought about the approach that would require to change the raw sql statement of getting the state from DB, maybe by utilizing join command on `state_changes_account` and `state_changes_data`, but this would be also an extra call to db and it will be quite heavy, so I decided to stick to this approach. I guess that in order to come up with the most optimal solution we need to change the way how we store `state_changes_data`
Before:
After:
=> fix: view state unknown account error

configuration/src/configs/mod.rs
`tx_details_storage` - is not required for state indexers
more details here: https://github.com/near/read-rpc/issues/304
=> (state-indexer): config.toml provisioning

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/middlewares.rs
In this PR we improve metrics view. 
We are collecting all method rates:
The main idea is to collect all unknown methods into one metric `method_not_found` to avoid confusion in the METHOD_CALLS_COUNTER metrics.
=> collecting METHOD_CALLS_COUNTER metrics improvement

configuration/src/configs/database.rs, configuration/src/configs/mod.rs, database/src/postgres/mod.rs
Migrations cannot be applied to read-only replicas
=> add read_only flag for database config

config.toml
This will allow you to quickly change the value in order to test and determine the optimal value.
=> add `prefetch_state_size_limit` into the `config.toml` as an env var

Cargo.lock, config.toml, configuration/Cargo.toml, configuration/src/configs/database.rs, configuration/src/configs/general.rs, configuration/src/configs/mod.rs, configuration/src/lib.rs
This PR introduces additional validation checks for certain configuration variables. Specifically, it ensures that all URLs and `f64` values adhere to their expected formats and constraints
Here's an example of running rpc-server with invalid env variables:
=> feat: added config checks

tx-indexer/src/collector.rs, tx-indexer/src/storage.rs
Now `save_outcomes_and_receipts` function manages data just like `save_finished_transaction_details`:
In case of successful saving outcome and receipt to shard it removes receipt from the watchlist. Otherwise, it pushes data back to the queue
=> feat: saving outcomes and receipts

Cargo.lock, readnode-primitives/Cargo.toml, readnode-primitives/src/lib.rs, rpc-server/src/modules/transactions/mod.rs
Since https://github.com/near/nearcore/pull/10676
the ReceiptEnumView has been changed to include `is_promise_yield` field
which is not present in the old version of the ReceiptEnumView
by deserializing the old version of the ReceiptEnumView and converting it to the new version
solved: https://github.com/near/read-rpc/issues/224
=> (rpc_server): fix transaction details borsh deserialize

rpc-server/src/main.rs, rpc-server/src/metrics.rs
This PR is adding more metrics based on the method name and returned error type (`ParseError`, `HandlerError` or `InternalError`)
Example:
closes #314
=> feat: added error metrics

tx-indexer/Cargo.toml, tx-indexer/src/collector.rs, tx-indexer/src/storage.rs
This PR affects `tx-indexer` for V2 only.
* Dropped the feature `validator` since we figured we don't need it anyway
* Added another feature `save_receipts_outcomes`. I made it default. When enabled, it saves data about receipts and outcomes to the database. 
The main idea behind a new feature is that we want to index/reindex only transaction details data stored in the bucket and don't want to do extra work related to storing receipt/outcome data in the DB. The feature is required in the "tip of the network" mode.
=> (tx-indexer): Drop `validator` feature along with code, add `save_receipts_outcomes` feature [by default]

cache-storage/src/lib.rs, database/src/base/state_indexer.rs, database/src/base/tx_indexer.rs, database/src/postgres/state_indexer.rs, logic-state-indexer/src/lib.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/utils.rs, tx-indexer/src/collector.rs, tx-indexer/src/main.rs, tx-indexer/src/storage.rs
This PR fixes a misconception behind `try_join` method. It doesn't await until the finish state of all futures, but rather kills other futures if one one them returns an error. You can try it yourself:
```rust
use anyhow::Result;
async fn a() -> Result<()> {
println!("Throwing an error");
anyhow::bail!("This is an error");
}
async fn b() -> Result<()> {
tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
println!("Returning OK");
Ok(())
}
#[tokio::main]
async fn main() -> Result<()> {
futures::try_join!(a(), b())?;
Ok(())
}
```
As you can see it doesn't print "Returning OK" to the stdout:
Now let's modify our code to use regular `join_all` instead and handle possible errors afterwards:
```rust
use anyhow::Result;
use futures::FutureExt;
async fn a() -> Result<()> { …
```
=> fix: removed `try_join` to await futures

.github/workflows/checks.yml, Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/config.rs, rpc-server/src/errors.rs, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/middlewares.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/clients/methods.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs, rpc-server/src/modules/queries/contract_runner/code_storage.rs, rpc-server/src/modules/queries/contract_runner/mod.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/state/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/modules/transactions/mod.rs, rpc-server/src/utils.rs
This migration would help us to:
- Implement custom status codes (200, 400, 404, 408 and 500) like we do it in jsonrpc
- Build a unified server configuration across jsonrpc and read-rpc
- Implement a public jsonrpc trait to have same definition of rpc methods
=> feat: migration from `jsonrpc-v2` to `actix`

rpc-server/src/modules/queries/methods.rs
In this pull request, we have added the ability to always request a state key by prefix without state_size_limit.
=> (rpc_server): allow to fetch state key by prefix without state_size_limit

rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs
**1. Add block_height_checker**
- Implemented a block_height_checker to ensure that non-existing blocks are not fetched. This improvement prevents unnecessary fetch attempts for blocks that do not exist, optimizing resource usage and reducing potential errors.
**2. Fix Bug with Fetch Chunk**
- Resolved a bug related to chunk fetching where the system was encountering issues with incomplete or incorrect chunk retrievals. This fix ensures that the chunk data is fetched correctly and reliably.
=> (rpc_server): Add `block_height_checker` and Fix Chunk Fetch Bug

.github/workflows/checks.yml
Cleaning up the workflows and repo. 
I have made a backup of the scylladb version of the readRPC (aka v1) to a separate branch `main-scylladb`. 
Also, I update the build workflows accordingly and dropping the `database-new` from the GH Actions workflow since we deprecate that branch (promoted to `main`)
=> chore: Drop `database-new` branch from GH workflow

CHANGELOG.md, database/src/postgres/state_indexer.rs, logic-state-indexer/src/lib.rs
This PR introduces significant improvements to the way state changes are inserted into the database. Previously, the system was making hundreds of individual requests per block, while we expected a maximum of 7 requests per block. This resulted in inefficiencies and a higher database load.
In this update, the logic for saving `state_changes` has been rewritten to use bulk inserts. Now, for each type of `state_changes`, only a single query is executed to perform a bulk insert, reducing the number of requests drastically and improving performance.
**Changes:**
- Refactored `state_changes` insertion logic to use bulk inserts.
- Reduced the number of database requests from hundreds to 7 or fewer per block.
This enhancement should improve overall performance and reduce database overhead.
=> (state-indexer-logic): improvement to bulk insert state changes

CHANGELOG.md, database/src/postgres/mod.rs, database/src/postgres/rpc_server.rs
In this PR, we have modified the query logic for fetching state data to avoid using `OFFSET`. Previously, using `OFFSET` in the query caused issues where empty pages were being returned intermittently. By switching to a paginated approach without relying on `OFFSET`, we aim to ensure more consistent and reliable retrieval of state data.
=> (rpc_server) fix: fetch state by pages

Cargo.lock, database/src/metrics.rs, database/src/postgres/rpc_server.rs, rpc-server/src/metrics.rs
This pull request introduces a new feature to track and count database read queries, aggregated by the following dimensions: `account_id`, `method_name`, `table_name`
The main objective is to collect detailed metrics to identify the most active accounts and understand their interaction patterns with the database. This data will be instrumental in optimizing database performance and usage patterns.
**Changes:**
* Added counters for database read queries categorized by `account_id`, `method_name`, and `table_name`.
* Integrated these metrics into the code.
This feature is designed to have minimal impact on the overall system performance while providing valuable insights for database management and optimization.
=> Add metric to count database reads queries by account_id, method_name and table_name

CHANGELOG.md, database/src/metrics.rs, database/src/postgres/rpc_server.rs, rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/contract_runner/mod.rs, rpc-server/src/modules/queries/methods.rs
We need to merge some necessary changes like supporting the new methods but we want to avoid updating nearcode because we have performance issues and some problems with memory leaks.
=> Cherry-pick necessary changes and avoid to update nearcore

logic-state-indexer/src/metrics.rs, tx-indexer/src/metrics.rs
This PR updates the configuration of the indexers metrics server to use only 2 workers. Since the metrics server workload is lightweight and does not require a large number of workers, reducing the count to 2 optimizes resource utilization without impacting performance.
The metrics server's operations are not resource-intensive, and a higher worker count is unnecessary. This change helps conserve system resources and ensures efficient operation.
=> Reduce Worker Count to 2 for Indexer Metrics Servers

rpc-server/src/utils.rs
When optimistic and final blocks stop updating together, the system still thinks that optimistic works correctly
=> fix(rpc-server): optimistic status is not working correctly

Cargo.lock, configuration/src/configs/general.rs, configuration/src/default_env_configs.rs, rpc-server/src/cache.rs, rpc-server/src/config.rs, rpc-server/src/health.rs, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/network/mod.rs, rpc-server/src/modules/queries/contract_runner/mod.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/state/methods.rs, rpc-server/src/utils.rs
This pull request enhances the cache layer for the `rpc_server `module, focusing on improving performance and fetching data from fastnear data.
**Key changes include:**
1. Added Chunks Cache
2. Improved Blocks Cache
3. Enhanced Contract Code Cache
These improvements collectively aim to boost the overall efficiency of the RPC server, particularly for high-demand scenarios.
=> (rpc_server): cache layer improvement

Cargo.lock, configuration/Cargo.toml, configuration/src/configs/tx_details_storage.rs, configuration/src/default_env_configs.rs, rpc-server/src/config.rs, tx-details-storage/Cargo.toml, tx-details-storage/src/lib.rs, tx-indexer/src/main.rs
This pull request introduces ScyllaDB as a new transaction storage backend. It integrates ScyllaDB to store and retrieve transaction data, providing an alternative to existing storage solutions.
**Key Changes**
1. Added connection setup and configuration for ScyllaDB.
2. Implemented methods for storing, querying, and managing transaction data.
This PR lays the groundwork for incorporating ScyllaDB into the system and may require subsequent optimizations based on production workloads.
=> Add ScyllaDB as a Transaction Storage
