near/read-rpc

rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs
This pr resolve unexpected proxy_calls counters. This counters increased every time we have encountered an unexpected error on the 100x RPC side so we can observe such metrics in Grafana.
=> DPLT-969: Unexpected proxy_calls counter

rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs
This pr implements  a set of metrics to accompany the unexpected proxy calls (metrics implemented in https://pagodaplatform.atlassian.net/browse/DPLT-969) so we can set up the Grafana in a more convenient way.
=> DPLT-1029: Total method hits counters

.github/workflows/checks.yml, rpc-server/src/modules/queries/utils.rs
=> chore: Add CI Rust checks

readnode-primitives/src/lib.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/utils.rs
1. Solved shadow data check ERROR:
`CHUNK`
`EXPERIMENTAL_TX_STATUS `
2. Add retry to NEAR JSON RPC.
=> [Tracking issue] Traffic mirroring caught errors

rpc-server/src/utils.rs
We get a lot of errors about not matching when using the `shadow_data_consistency` feature.  
This often happens through different ordering of keys in the object. 
The basic idea is to sort the json responses before comparing them. 
This PR implements 2 functions for json sorting. 
The first `json_sort_value` sorts the keys using BTreeMap. 
The second `generate_array_key` is an additional function for sorting arrays. 
The idea is to sort the elements in the array by the values of the keys of the objects in the array.
I think it affects the performance of the service, but it should help us understand if our service is working correctly
=> DPLT-1038: EXPERIMENTAL_tx_status receipts order

rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/storage.rs, rpc-server/src/utils.rs
Improvement  query view_code error handling
NO_CONTRACT_CODE when there is an account but no contract code
UNKNOWN_ACCOUNT when there is no contract code AND no account
=> DPLT-1039: `query.view_code`

rpc-server/src/storage.rs
In PR #105  I've introduced a few bugs in ScyllaDB results interpretation (I've swapped the blob with varint 🤦‍♂️)
=> fix(rpc-server): Fix bug introduced by storage refactoring

perf-testing/README.md
Add new numbers without shadow consistency checks
=> Update perf tests README.md

tx-indexer/src/config.rs
In this PR we rewrite queries to get transactions and get receipts on prepared queries
=> (tx-indexe) query improvement

epoch-indexer/Cargo.toml, readnode-primitives/src/lib.rs, rpc-server/Cargo.toml, state-indexer/Cargo.toml, tx-indexer/Cargo.toml
In this PR we fixed a small bug in `EXPERIMENTAL_receipt`.
=> fix parse receipt_id

epoch-indexer/src/lib.rs
On the mainnet we have a few epochs that start epoch height with no existing block. 
Then we got an infinity loop to try to fetch no existing block.
=> improvement epoch indexer to avoid fetch block infinity loop

README.md, docs/CUSTOM_RPC_METHODS.md, docs/RPC_METHODS.md, rpc-server/README.md
In this pr, we extend documentation and add a description about rpc methods state and add documentation about custom rpc methods.
=> Add documentation

CHANGELOG.md, Cargo.toml, configuration/Cargo.toml, database/Cargo.toml, epoch-indexer/Cargo.toml, perf-testing/Cargo.toml, readnode-primitives/Cargo.toml, rpc-server/Cargo.toml, state-indexer/Cargo.toml, tx-indexer/Cargo.toml
- nearcore v1.36.0
- rust v1.73.0
=> chore: release v0.1.0

CHANGELOG.md, rpc-server/src/main.rs, rpc-server/src/metrics.rs
This pull request addresses the issue #183 
1. Add a total request counter.
2. Increment the total request counter before executing request.
=> Total requests metrics

configuration/example.config.toml, configuration/src/lib.rs, near-state-indexer/src/main.rs, near-state-indexer/src/utils.rs, rpc-server/Cargo.toml, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/utils.rs
This pull request addresses several key improvements:
**1. Default Logging Level:**
- Added RUST_LOG=info as the default directive to enhance visibility and provide informative logs for better troubleshooting and monitoring.
**2. Enhanced Near-State-Indexer Logs:**
- Included additional informational logs at the start of the near-state-indexer process, providing deeper insights into its functionality and progress.
**3. Optimistic Block Update Handling:**
- Implemented a handler to check the regularity of optimistic block updates.
- If updates are irregular, the system initiates an update task to synchronize the final block from the lake, ensuring data consistency and integrity.
These enhancements aim to streamline the logging process for improved observability and to fortify the system's …
=> Enhancement: Improve Logging and Optimistic Block Update Handling

rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/utils.rs
This pull request introduces two significant changes aimed at enhancing the performance and monitoring capabilities of our system's optimistic request handling.
**New Metric: PROXY_OPTIMISTIC_REQUESTS_TOTAL**
- In this update, we add a new metric called PROXY_OPTIMISTIC_REQUESTS_TOTAL. This metric is designed to accurately calculate all proxied optimistic requests processed by the system. By tracking these requests, we gain valuable insights into the usage and effectiveness of optimistic request handling, enabling better optimization and resource allocation.
**Improvement in Optimistic Block Updating Handler**
- This pull request also includes enhancements to the handler responsible for checking the regularity of optimistic block updating. By improving this handler, we ensure more …
=> Extending and improvement optimistic handler

Cargo.lock, configuration/Cargo.toml, configuration/src/configs/general.rs, near-state-indexer/Cargo.toml, rpc-server/Cargo.toml, rpc-server/src/cache.rs, rpc-server/src/config.rs, rpc-server/src/health.rs, rpc-server/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/utils.rs, tx-indexer/src/collector.rs
**Changes Introduced:**
1. **Improvement of Redis Subscribers:**
- Enhanced Redis subscribers to support both optimistic and final block scenarios.
- Optimized handling for better performance and reliability during block processing.
2. **RwLock Wrapper for LruMemoryCache:**
- Implemented a RwLock wrapper for LruMemoryCache to facilitate safe usage of the cache across multiple threads.
- Ensures thread-safety and prevents potential race conditions when accessing and modifying cached data.
3. **Optimization of BlocksInfoByFinality:**
- Split BlocksInfoByFinality into different RwLocks to enhance performance and access efficiency.
- By segregating the locks, improved concurrency and reduced contention when accessing blocks information based on finality.
**Purpose:**
This pull request aims to …
=> Improvement cache storage for finalities blocks

near-state-indexer/src/main.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/queries/methods.rs
This pull request focuses on enhancing the performance and reliability of the RPC server module, specifically targeting the handling of optimistic blocks and addressing potential memory leaks within the codebase.
**Key Changes:**
1. **Optimistic Block Handling Improvement:** Implemented optimizations to streamline the processing of optimistic blocks, enhancing the efficiency and responsiveness of the RPC server.
2. **Memory Leak Prevention:** Conducted a thorough review and refactoring to identify and rectify any instances of memory leaks within the code. This ensures better resource management and overall stability of the server.
These enhancements contribute to a more robust and efficient RPC server, promoting smoother operation and improved resource utilization.
=> (rpc_server): optimistic handle improvement. Code optimisation to avoid memory leaks.

rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/utils.rs
More details read in this issue: https://github.com/near/read-rpc/issues/231
=> Improve the proxy to be smarter

.github/workflows/checks.yml, Cargo.lock, Cargo.toml, rpc-server/Cargo.toml, rpc-server/src/main.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/utils.rs
This pull request introduces several key enhancements and optimizations to the project, focusing on memory management, build profiles, and control over contract compilation. Below are the key changes implemented:
1. **Integration of mimalloc:** This update adopts the mimalloc memory allocator for improved memory management within the project. Leveraging mimalloc's efficiency and performance benefits, we expect to observe reduced memory fragmentation and overall better utilization, particularly under high load scenarios.
2. **Refined Cargo Profile Settings:** The Cargo build profiles have been adjusted to optimize the project's build process. 
3. **Manual Contract Compilation Control:** This empowers developers to specify when and how contract compilation occurs, offering greater …
=> memory usage improvement

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/errors.rs, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/middlewares.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/clients/methods.rs, rpc-server/src/modules/gas/methods.rs, rpc-server/src/modules/network/methods.rs, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/receipts/methods.rs, rpc-server/src/modules/transactions/methods.rs, rpc-server/src/utils.rs
This pull request focuses on refactoring and improving the metrics system within the rpc_server module. The changes enhance the clarity, efficiency, and extensibility of the metrics collection and reporting processes.
**Refactoring of Metrics Codebase:**
- Reorganized metrics-related code into a dedicated module for better modularity and maintainability.
- Simplified the metrics collection logic by removing redundant or outdated code.
- Enhanced the readability of metrics-related functions with clearer naming conventions and comments.
**Optimization of Metrics Collection:**
- Improved the efficiency of the metrics collection process to reduce overhead.
- Utilized more efficient data structures to store and process metrics.
- Introduced batching for metrics reporting to decrease the …
=> (rpc_server): metrics refactoring and improvements

Cargo.lock, rpc-server/src/modules/queries/methods.rs, rpc-server/src/modules/queries/mod.rs, rpc-server/src/modules/queries/utils.rs, rpc-server/src/modules/state/methods.rs, rpc-server/src/modules/state/utils.rs, rpc-server/src/utils.rs
1. Enhanced Tracing: Improved tracing instrumentation to provide more detailed and actionable logs.
2. Performance Monitoring: Added comprehensive logging to monitor RPC server performance and identify bottlenecks.
=> (rpc_server):improvement tracing instrument logs

database/src/scylladb/rpc_server.rs
This reverts commit 2e4dc302ae0e93e2c75706b840ecb72cb7cf2040.
Transaction should return from later blocks. 
56t8ceK2B8BympLJ6gPL3CYsdPMJiWSegsCEFsAhcAj7 - need investidate in future
=> Revert https://github.com/near/read-rpc/pull/261

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/RPC_METHODS.md
=> chore: relese v0.2.9

rpc-server/Dockerfile, state-indexer/Dockerfile, tx-indexer/Dockerfile
Build is failing because I forgot to update `Dockerfile`s. Here's the fix
=> fix: Add tx-details-storage into Dockerfiles

Cargo.lock, configuration/Cargo.toml, configuration/src/configs/tx_details_storage.rs, tx-details-storage/Cargo.toml, tx-details-storage/src/lib.rs, tx-indexer/Cargo.toml, tx-indexer/src/collector.rs, tx-indexer/src/metrics.rs
This pull request refactors the storage implementation for transaction details. Previously, the AWS SDK was utilized for managing storage operations. In this update, we have replaced the AWS SDK with the google-cloud-storage crate to integrate with Google Cloud Storage.
**Changes Made:**
1. Removed dependencies on the AWS SDK from tx-details-storage.
2. Added the google-cloud-storage crate.
3. Refactored storage service implementations to use Google Cloud Storage.
4. Updated configuration settings to accommodate Google Cloud Storage credentials and setup.
5. Extend metrics for the tx-indexer to monitor the collecting transaction process.
6. Refactoring and improvement mechanism to save and validate transactions.
=> (tx-details-storage): Using crate google-cloud-storage 

Cargo.lock, configuration/Cargo.toml, configuration/src/configs/tx_details_storage.rs, rpc-server/Dockerfile, tx-details-storage/Cargo.toml, tx-details-storage/src/lib.rs, tx-indexer/Cargo.toml, tx-indexer/Dockerfile, tx-indexer/src/collector.rs, tx-indexer/src/metrics.rs
* Changes to `tx-indexer` (switch to `google_cloud_storage`)
=> chore: Merge develop with main

configuration/src/configs/mod.rs
Dublicate for develop branche: https://github.com/near/read-rpc/pull/305
=> (state-indexer): config.toml provisioning

Cargo.lock, readnode-primitives/Cargo.toml, readnode-primitives/src/lib.rs, rpc-server/src/modules/transactions/mod.rs
cherry-pick https://github.com/near/read-rpc/pull/317
=> fix transaction details borsh deserialize

Cargo.lock, rpc-server/Cargo.toml, rpc-server/src/main.rs
This PR is a continuation of #316
Improved code quality by adding a custom trait for `jsonrpc_v2::ServerBuilder`
=> refactor: removed macro with custom trait implementation

database/src/postgres/state_indexer.rs, logic-state-indexer/Cargo.toml, rpc-server/src/config.rs
=> chore: made clippy happy

Cargo.lock, Cargo.toml, cache-storage/src/lib.rs, config.toml, configuration/Cargo.toml, configuration/example.config.toml, configuration/src/configs/lake.rs, near-state-indexer/Cargo.toml, near-state-indexer/src/main.rs, near-state-indexer/src/utils.rs, rpc-server/src/config.rs, rpc-server/src/main.rs, rpc-server/src/metrics.rs, rpc-server/src/modules/blocks/methods.rs, rpc-server/src/modules/blocks/mod.rs, rpc-server/src/modules/blocks/utils.rs, rpc-server/src/utils.rs, state-indexer/src/main.rs, tx-indexer/src/main.rs
This reverts commit ec9bed7133f9cb772b57edbd215084d0d543f0b1.
=> Revert "migrate to fastnear (#355)"

database/src/metrics.rs, database/src/postgres/rpc_server.rs
https://github.com/near/read-rpc/pull/379
=> cherry-pick removed metrics

CHANGELOG.md, Cargo.lock, Cargo.toml
- nearcore v2.6.2
- rust v1.85.0
=> update nearcore to 2.6.2
